from enum import Enum

class FileExtension(Enum):
    TXT = ".txt"
    PDF = ".pdf"
    DOC = ".doc"
    DOCX = ".docx"
    XLS = ".xls"
    XLSX = ".xlsx"
    CSV = ".csv"
    JSON = ".json"
    XML = ".xml"
    HTML = ".html"
    JPEG = ".jpeg"
    JPG = ".jpg"
    PNG = ".png"
    GIF = ".gif"
    MP3 = ".mp3"
    MP4 = ".mp4"
    AVI = ".avi"
